# Copyright Greg Haskins All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
FROM _BASE_NS_/fabric-baseimage:_BASE_TAG_ as builder
WORKDIR /opt/gopath
RUN mkdir src && mkdir pkg && mkdir bin
ADD . src/github.com/hyperledger/fabric
WORKDIR /opt/gopath/src/github.com/hyperledger/fabric
ENV EXECUTABLES go git curl
RUN make configtxgen configtxlator cryptogen peer discover idemixgen

FROM _BASE_NS_/fabric-baseimage:_BASE_TAG_
ENV FABRIC_CFG_PATH /etc/hyperledger/fabric
RUN apt-get update && apt-get install -y jq
VOLUME /etc/hyperledger/fabric
COPY --from=builder /opt/gopath/src/github.com/hyperledger/fabric/.build/bin /usr/local/bin
COPY --from=builder /opt/gopath/src/github.com/hyperledger/fabric/sampleconfig $FABRIC_CFG_PATH



# BEGIN: Python HoneyBadgerMPC dependencies                                  #
ENV PYTHONUNBUFFERED=1

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly-2018-10-24

ENV PATH /root/.cargo/bin:$PATH

# Install Python 3.7

RUN apt-get update && apt-get install -y git locales zlib1g-dev python3-pip libffi-dev libgmp-dev libmpc-dev libmpfr-dev libntl-dev libflint-dev build-essential checkinstall zlib1g zlib1g-dev openssl libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev


# RUN gpg --recv-key AA65421D

RUN wget https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tgz

RUN wget https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tgz.asc

# RUN gpg --verify Python-3.7.2.tgz.asc
RUN cp Python-3.7.2.tgz /usr/src/
RUN cd /usr/src && tar -zxvf Python-3.7.2.tgz

RUN cd /usr/src/Python-3.7.2
RUN cd /usr/src/Python-3.7.2 && ./configure
RUN cd /usr/src/Python-3.7.2 && make altinstall

# Download and install honeybadgerMPC


RUN pip3.7 install --upgrade pip

RUN pip3.7 install pyyaml

RUN cp /usr/local/bin/python3.7 /usr/bin/python

RUN cd /usr/src 

RUN cd /usr/src/ && git clone https://github.com/hybridNeo/HoneyBadgerMPC.git

RUN cd /usr/src/HoneyBadgerMPC && git checkout dev



WORKDIR /usr/src/HoneyBadgerMPC

RUN cd /usr/src/HoneyBadgerMPC && pip3.7 install pairing/

RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
    ENV LANG en_US.UTF-8  
    ENV LANGUAGE en_US:en  
    ENV LC_ALL en_US.UTF-8 


# This is needed otherwise the build for the power sum solver will fail.
# This is a known issue in the version of libflint-dev in apt.
# https://github.com/wbhart/flint2/issues/217
# This has been fixed if we pull the latest code from the repo. However, we want
# to avoid compiling the lib from the source since it adds 20 minutes to the build.
# TODO change branch to hyperbadgermpc
RUN sed -i '30c #include "flint/flint.h"' /usr/include/flint/flintxx/flint_classes.h

ARG BUILD

# RUN pip3 install --no-cache-dir -e git+https://github.com/initc3/HoneyBadgerMPC.git@dev 
RUN pip3 install git+https://github.com/initc3/HoneyBadgerMPC.git@dev


# END: Python HoneyBadgerMPC dependencies                                    #
##############################################################################


